<?php
/**
 * Created by PhpStorm.
 * User: 旭
 * Date: 2019/5/28
 * Time: 22:54
 */

namespace app\admin\controller;

use app\admin\model\Postdata;
use app\admin\model\Usersdata;
use think\Controller;
use think\Model;
use think\Request;
use think\Session;


class Comment extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (Session::has("users_name") && Session::has("users_id")) {
            //记录访客信息

        } else {
            //提示登陆
            $this->error('请登录', 'admin/login/login');
        }

    }

    public function index()
    {
//查询所有帖子的 picture_id
        $picture_res = Postdata::where('post_id', '>=', 0)->select();

        foreach ($picture_res as $key) {
            $sql_picture_res[] = $key->getData();

        }
        if (!empty($sql_picture_res)) {
            if (count($sql_picture_res) > 0) {
//    有数据
//获取用户名信息,进行拼接
                for ($i = 0; $i < count($sql_picture_res); $i++) {
                    $sql_users_info[] = Usersdata::get(['users_id' => $sql_picture_res[$i]['post_users_id']])->getData();
                    $sql_picture_res[$i] += $sql_users_info[$i];
                }
            } else {
                return $this->error('用户数据出错啦!');
            }

        } else {
            $sql_picture_res = '没有数据';
        }
//        dump($sql_picture_res);
//        dump($sql_users_info);

        $this->assign('post_data', $sql_picture_res);

        return $this->fetch();
    }

    public function send()
    {
        return $this->fetch();
    }

    public function create_post()
    {
        $reuqest = Request::instance();
        $info = "";
        $post_head = $reuqest->post('post_head');
        $post_body = $reuqest->post('post_body');
        $files = $reuqest->file('image');

        if (!empty($files)) {
//            带图片
//            检查数据
            $data = [
                'post_head' => $post_head,
                'post_body' => $post_body,
            ];
            $judgement = $this->validate($data, 'Comment.new_post');

            foreach ($files as $picFile) {
                // 移动到框架应用根目录/public/uploads/images/ 目录下
//                $info = $picFile->move(ROOT_PATH . 'uploads' . DS . 'images');
                $info = $picFile->move(ROOT_PATH . 'public' . DS . 'uploads' . DS . 'images');
                /*获取存储路径，以便插入数据库*/
                $path = "/work/minshop/public/uploads/images/" . $info->getSaveName();
//                echo $path;
            }

            if ($info !== "") {
//            return $this->success('上传成功！');
                // 成功上传后 获取上传信息
                // 输出 jpg
//                echo $info->getExtension();
                // 输出 42a79759f284b767dfcb2a0197904287.jpg
//                echo $info->getFilename();
                $create_time = date('Y-m-d H:i:s', time());
                $post_user_id = Session::get('users_id');
                $sql_data_post = [
                    'post_users_id' => $post_user_id,
                    'post_head' => $post_head,
                    'post_desn' => $post_body,
                    'post_create_time' => $create_time,
                    'post_picture_url' => $path,
                ];
                $new_post = Postdata::insert($sql_data_post);
                if ($new_post == 1) {
                    return $this->success('成功嗷!');
                } else {
                    return $this->error('插入失败');
                }

            } else {
//             上传失败获取错误信息
                /* echo $file->getError();*/
                return $this->error('上传失败！');
            }
        } else {
//            不带图片
//            检查数据
            $data = [
                'post_head' => $post_head,
                'post_body' => $post_body,
            ];
            $judgement = $this->validate($data, 'Comment.new_post');
            if (true === $judgement) {
                $post_user_id = Session::get('users_id');
                $create_time = date('Y-m-d H:i:s', time());
                $sql_data = [
                    'post_users_id' => $post_user_id,
                    'post_head' => $post_head,
                    'post_desn' => $post_body,
                    'post_create_time' => $create_time,
                ];
                $res_sql = Postdata::insert($sql_data);
                if ($res_sql) {
                    return $this->success('成功嗷!');
                } else {
                    return $this->error('插入失败');
                }


            } else {
                return $this->error($judgement);
            }
        }


    }
}