<?php

namespace app\index\controller;

use think\Controller;
use think\Request;
use think\Session;

class Index extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (Session::has("users_name") && Session::has("users_id")){
            //正常执行
        }else{
            //非正常操作
            $this->redirect('index/login/login');
        }
    }


    public function index()
    {
        return $this->fetch();
    }

    public function admin()
    {
        return $this->fetch();
    }


}
