<?php

namespace app\index\controller;

use think\Controller;
use think\Request;
use think\Session;

class Index extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //check login status
        if (Session::has("users_name") && Session::has("users_id")){
            //记录访客信息
        }else{
            //提示登陆
            $this->redirect('index/login/login');
        }
    }


    public function index()
    {
        //new user num
        //new order num
        //page view
        //on-line user
        //volume
        //

        return $this->fetch();
    }

    public function admin()
    {
        return $this->fetch();
    }
    public function icon(){
        return $this->fetch();
    }


}
